pipeline {
    agent any
    tools {         
        maven 'maven-3.9.2'  // Ensure this matches the name in Global Tool Configuration
        jdk 'java-11'       // Ensure this matches the name in Global Tool Configuration
    }
    stages {
        stage("Clean up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Update Maven Version Requirement") {
            steps {
                dir("simple-java-maven-app") {
                    sh "sed -i 's/\\[3.9.2,/\\[3.8.7,/g' pom.xml"
                }
            }
        }
        stage("Verify Maven Version") {
            steps {
                sh "mvn -version"
            }
        }
        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
                }
            }
        }
    }
}
